version: '3.8'

services:
  # Vector Database - Qdrant
  mem0_store:
    image: qdrant/qdrant:latest
    container_name: openmemory-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - openmemory_network

  # Graph Database - Memgraph with MAGE
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: openmemory-memgraph
    restart: always
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=INFO", "--also-log-to-stderr"]
    environment:
      - MEMGRAPH_USER=memgraph
      - MEMGRAPH_PASSWORD=memgraph
    volumes:
      - memgraph_data:/usr/lib/memgraph
    networks:
      - openmemory_network

  # Memgraph Lab - UI for Graph Database
  memgraph-lab:
    image: memgraph/lab:latest
    container_name: openmemory-memgraph-lab
    restart: always
    ports:
      - "3001:3000"
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
    depends_on:
      - memgraph
    networks:
      - openmemory_network

  # OpenMemory MCP Server
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    build: 
      context: ./openmemory/api
      dockerfile: Dockerfile
    container_name: openmemory-mcp-server
    restart: always
    ports:
      - "8765:8765"
    env_file:
      - .env
    environment:
      # Pass through the API keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMBED_KEY=${OPENAI_EMBED_KEY}
      # Embedder configuration
      - MEM0_EMBEDDER_PROVIDER=openai
      - MEM0_EMBEDDER_CONFIG_MODEL=text-embedding-3-large
      # Override specific settings for Graph Memory
      - MEM0_GRAPH_STORE_PROVIDER=memgraph
      - MEM0_GRAPH_STORE_CONFIG_URL=bolt://memgraph:7687
      - MEM0_GRAPH_STORE_CONFIG_USERNAME=memgraph
      - MEM0_GRAPH_STORE_CONFIG_PASSWORD=memgraph
      # Ensure vector store points to our Qdrant instance
      - MEM0_VECTOR_STORE_CONFIG_HOST=mem0_store
      - MEM0_VECTOR_STORE_CONFIG_PORT=6333
    depends_on:
      - mem0_store
      - memgraph
    volumes:
      - ./openmemory/api:/usr/src/openmemory
      - openmemory_data:/usr/src/openmemory/data
    command: uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4
    networks:
      - openmemory_network

  # OpenMemory UI
  openmemory-ui:
    build:
      context: ./openmemory/ui
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    container_name: openmemory-ui
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=${USER:-default}
    depends_on:
      - openmemory-mcp
    networks:
      - openmemory_network

networks:
  openmemory_network:
    driver: bridge
    name: openmemory_network

volumes:
  qdrant_storage:
    driver: local
  memgraph_data:
    driver: local
  openmemory_data:
    driver: local 