services:
  mem0_store:
    restart: always
    image: qdrant/qdrant
    ports:
      - "6334:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
  openmemory-mcp:
    restart: always
    image: mem0/openmemory-mcp
    build: api/
    environment:
      - OPENAI_OR_KEY=${OPENAI_OR_KEY}
      - OPENAI_EMBED_KEY=${OPENAI_EMBED_KEY}
      - OPENAI_API_KEY=${OPENAI_EMBED_KEY}   # legacy fallback
      - USER=${USER}
      - API_KEY
    env_file:
      - api/.env
    depends_on:
      - mem0_store
    ports:
      - "8766:8765"
    volumes:
      - ./api:/usr/src/openmemory
      - ./data/api:/data
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
  openmemory-ui:
    restart: always
    build:
      context: ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${USER}
